### ISSUE TITLE
Clean the outputs of the notebooks

### ISSUE THREAD

**Issue by vmesel** [maponti/ml_statistical_learning#2]
Hey @joaogui1 I think we should keep the outputs of the notebooks clean, that way, people will see the result by theirselves. What do you think?

**Comment by joaogui1** [comment]
Cara, acho que a pessoa devia ver o resultado quando ela tiver rodando o notebook, não entendi exatamente o que você preferia.

**Comment by vmesel** [comment]
Dá uma olhada nesse notebook: https://github.com/maponti/ml_statistical_learning/blob/master/Notebooks/chapter2/independency.ipynb

No seu último commit neste [notebook](https://github.com/maponti/ml_statistical_learning/blob/master/Notebooks/chapter1/mlp.ipynb) tu deixou alguns outputs do seu computador! Não seria melhor tira-lo?

**Comment by joaogui1** [comment]
Aaaah, mil perdões, isso não era para fazer parte da mudança.
